#+hugo_base_dir: ../

* Trade deficits aren't necessarily bad! :economics:
:PROPERTIES:
:EXPORT_FILE_NAME: trade-deficits-not-bad
:EXPORT_DATE: [2025-04-06 Sun]
:END:

Noah Smith [[https://www.noahpinion.blog/p/trade-deficits-do-not-make-a-country][challenges]] the common perception of trade deficits, using the credit card analogy to illustrate that they represent acquiring more goods in exchange for future financial obligations. This perspective helps us understand how South Korea, for example, leveraged trade deficits to fuel rapid industrial growth, particularly in its manufacturing sector, by importing necessary capital goods. However, the US experience with China demonstrates the potential for trade deficits to contribute to deindustrialization, as seen in the decline of American steel and textile industries. Therefore, while addressing deindustrialization is crucial, tariffs offer a simplistic and potentially harmful solution.
* Mounting Synology folder share on linux :linux:
:PROPERTIES:
:EXPORT_FILE_NAME: mount-synology-on-linux
:EXPORT_DATE: [2025-04-05 Sat]
:END:

Accessing files stored on your Synology NAS directly from your Linux machine can be very convenient, whether it's for managing media libraries, accessing shared documents, or performing backups. This guide provides quick steps to mount a Synology share on Ubuntu or its derivatives (like Pop!_OS) using the CIFS protocol, ensuring it's available even after a reboot.
#+hugo: more
** Prerequisites
- On your Synology, go to Control Panel -> File Services -> SMB and check the 'Enable SMB service' option.
- On your linux machine, install CIFS Utilities
#+begin_src shell
sudo apt update
sudo apt install cifs-utils
#+end_src
- Create a mount point where the Synology share will be accessible. Let's use /mnt/nas_media as an example.
~sudo mkdir /mnt/nas_media~

** Temporary mount (for testing)
First, let's test if we can mount the share manually. This mount will not survive a reboot. Make sure to use your synology username and password in the command.

#+begin_src shell
# Find your user ID (uid) and group ID (gid) - often 1000 for the first user
id

# Mount the share
sudo mount -t cifs -o username=YourUsername,password=YourPassword,uid=1000,gid=1000 //synology_ip/Media /mnt/nas_media
#+end_src

To unmount
~sudo umount /mnt/nas_media~

** Persistent Mount
To make the mount available after a reboot, we need to add an entry in /etc/fstab. But /etc/fstab is world readable, so let's first put the credentials in a secure file.

#+begin_src shell
cat >> /root/.smbNas<<EOF
username=YourUsername
password=YourPassword
EOF

# Restrict access to the file to only root.
sudo chmod 600 /root/.smbNas
#+end_src

Now add the entry to /etc/fstab using the credentials file created above.
#+begin_src shell
//synology_ip/Media /mnt/nas_media cifs credentials=/root/.smbNas,uid=1000 0 0
#+end_src

Now trigger the mount using ~sudo mount -a~ or by rebooting the machine.
