#+hugo_base_dir: ../

* Streamline Org-Mode Capture: Disable Browser Prompts for Org-Protocol :emacs:orgmode:
:PROPERTIES:
:EXPORT_FILE_NAME: disable-browser-prompts-org-protocol
:EXPORT_DATE: [2025-04-07 Mon]
:END:

I use emacs org-mode to capture links from the browser for later reading, or for archiving. For this purpose, I use a simple [[https://www.gnu.org/software/emacs/manual/html_node/org/The-capture-protocol.html][bookmarklet]] to capture the link, title and any selected text, and then use an org-capture template to store the information. However, when i click on the bookmarklet, most browsers throw a pop-up asking for permission to open org-protocol:// links. This security check, while well-intentioned, adds friction every time I try to capture a link.
Here's how we can disable this confirmation prompt on Chromium based browsers.
#+hugo: more

** On macOS
#+begin_src shell
# For Google Chrome
defaults write com.google.Chrome URLAllowlist -array-add -string 'org-protocol://*'

# For Brave
defaults write com.brave.Browser URLAllowlist -array-add -string 'org-protocol://*'
#+end_src

** On Linux
We can achieve this using enterprise policy files. This however will apply to all users on the machine for this browser.
#+begin_src shell
mkdir -p /etc/opt/chrome/policies/{managed,recommended}
cat <<EOF >/etc/opt/chrome/policies/managed/allow_org_protocol.json
{
  "URLAllowlist": [
    "org-protocol:*"
  ]
}
EOF
#+end_src
The above command works for Chrome, but Brave seems to store the policies at /etc/brave/policies, so update the paths accordingly.

To debug whether policies were loaded, go to chrome://policy or brave://policy, and check logs. You can also reload policies here without having to restart chrome/brave.

* Trade deficits aren't necessarily bad! :economics:
:PROPERTIES:
:EXPORT_FILE_NAME: trade-deficits-not-bad
:EXPORT_DATE: [2025-04-06 Sun]
:END:

Noah Smith [[https://www.noahpinion.blog/p/trade-deficits-do-not-make-a-country][challenges]] the common perception of trade deficits, using the credit card analogy to illustrate that they represent acquiring more goods in exchange for future financial obligations. This perspective helps us understand how South Korea, for example, leveraged trade deficits to fuel rapid industrial growth, particularly in its manufacturing sector, by importing necessary capital goods. However, the US experience with China demonstrates the potential for trade deficits to contribute to deindustrialization, as seen in the decline of American steel and textile industries. Therefore, while addressing deindustrialization is crucial, tariffs offer a simplistic and potentially harmful solution.
* Mounting Synology folder share on linux :linux:
:PROPERTIES:
:EXPORT_FILE_NAME: mount-synology-on-linux
:EXPORT_DATE: [2025-04-05 Sat]
:END:

Accessing files stored on your Synology NAS directly from your Linux machine can be very convenient, whether it's for managing media libraries, accessing shared documents, or performing backups. This guide provides quick steps to mount a Synology share on Ubuntu or its derivatives (like Pop!_OS) using the CIFS protocol, ensuring it's available even after a reboot.
#+hugo: more
** Prerequisites
- On your Synology, go to Control Panel -> File Services -> SMB and check the 'Enable SMB service' option.
- On your linux machine, install CIFS Utilities
#+begin_src shell
sudo apt update
sudo apt install cifs-utils
#+end_src
- Create a mount point where the Synology share will be accessible. Let's use /mnt/nas_media as an example.
~sudo mkdir /mnt/nas_media~

** Temporary mount (for testing)
First, let's test if we can mount the share manually. This mount will not survive a reboot. Make sure to use your synology username and password in the command.

#+begin_src shell
# Find your user ID (uid) and group ID (gid) - often 1000 for the first user
id

# Mount the share
sudo mount -t cifs -o username=YourUsername,password=YourPassword,uid=1000,gid=1000 //synology_ip/Media /mnt/nas_media
#+end_src

To unmount
~sudo umount /mnt/nas_media~

** Persistent Mount
To make the mount available after a reboot, we need to add an entry in /etc/fstab. But /etc/fstab is world readable, so let's first put the credentials in a secure file.

#+begin_src shell
cat >> /root/.smbNas<<EOF
username=YourUsername
password=YourPassword
EOF

# Restrict access to the file to only root.
sudo chmod 600 /root/.smbNas
#+end_src

Now add the entry to /etc/fstab using the credentials file created above.
#+begin_src shell
//synology_ip/Media /mnt/nas_media cifs credentials=/root/.smbNas,uid=1000 0 0
#+end_src

Now trigger the mount using ~sudo mount -a~ or by rebooting the machine.
